#!/usr/bin/env sh

_() {
  YEAR="1970"

  echo "GitHub Username: "
  read -r USERNAME

  echo "GitHub Access token: "
  read -r ACCESS_TOKEN

  [ -z "$USERNAME" ] && exit 1
  [ -z "$ACCESS_TOKEN" ] && exit 1

  REPO="test-commit-in-${YEAR}"
  DIR="${YEAR}-history"

  [ -d "$DIR" ] && rm -rf "$DIR"
  mkdir "$DIR"
  cd "$DIR" || exit

  git init

  echo "# ${YEAR} - Commit History 🕰️

This repository simulates historical commits made in ${YEAR}.

👤 Author: [$USERNAME](https://github.com/$USERNAME)  
✍️ Generated by: https://github.com/EsmailEbrahim/1970-script
" > README.md

  git add README.md
  GIT_AUTHOR_DATE="${YEAR}-01-01T12:00:00" \
  GIT_COMMITTER_DATE="${YEAR}-01-01T12:00:00" \
  git commit -m "1970: The Unix epoch begins"

  # Historical commit messages (date | message)
  COMMITS="
1970-04-07|RFC 1 published – ARPANET documentation begins
1970-06-01|Unix gains more internal users at Bell Labs
1970-08-15|Early C language development underway
1970-10-29|ARPANET nodes continue to expand
1970-12-31|Closing the first year of Unix
"

  echo "$COMMITS" | while IFS="|" read -r DATE MESSAGE; do
    echo "$MESSAGE" >> history.txt
    git add history.txt

    GIT_AUTHOR_DATE="${DATE}T18:00:00" \
    GIT_COMMITTER_DATE="${DATE}T18:00:00" \
    git commit -m "$MESSAGE"
  done

  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${REPO}.git"
  git branch -M main
  git push -u origin main -f

  cd ..
  rm -rf "$DIR"

  echo
  echo "Done! Check your history: https://github.com/${USERNAME}"
} && _

unset -f _
