#!/usr/bin/env sh

_() {
  START_YEAR=1970
  END_YEAR=2026

  echo "GitHub Username: "
  read -r USERNAME

  echo "GitHub Access token: "
  read -r ACCESS_TOKEN

  [ -z "$USERNAME" ] && exit 1
  [ -z "$ACCESS_TOKEN" ] && exit 1

  REPO="test-commit-history"
  DIR="history-timeline"

  [ -d "$DIR" ] && rm -rf "$DIR"
  mkdir "$DIR"
  cd "$DIR" || exit

  git init

  echo "# Tech History Timeline 🕰️

This repository is a storytelling experiment using Git commit history.

Each commit represents a major moment in computing history.

👤 Author: [$USERNAME](https://github.com/$USERNAME)  
✍️ Generated by: https://github.com/EsmailEbrahim/1970-script
" > README.md

  git add README.md
  GIT_AUTHOR_DATE="1970-01-01T12:00:00" \
  GIT_COMMITTER_DATE="1970-01-01T12:00:00" \
  git commit -m "1970: UNIX is born"

  HISTORY="
1971|1971: First email is sent
1972|1972: C programming language emerges
1973|1973: Ethernet is invented
1974|1974: TCP/IP is proposed
1975|1975: Microsoft is founded
1976|1976: Apple is founded
1977|1977: First personal computers reach consumers
1978|1978: Spam email is sent for the first time
1979|1979: Usenet is created
1980|1980: IBM enters the personal computer market
1981|1981: MS-DOS is released
1982|1982: The term \"Internet\" is officially used
1983|1983: TCP/IP becomes the Internet standard
1984|1984: Apple launches the Macintosh
1985|1985: Windows 1.0 is released
1986|1986: NSFNET expands Internet access
1987|1987: First major computer virus spreads
1988|1988: Morris Worm highlights Internet security risks
1989|1989: World Wide Web is proposed
1990|1990: The first web browser is created
1991|1991: Linux kernel is released
1992|1992: The Internet goes public
1993|1993: Mosaic web browser popularizes the web
1994|1994: Netscape is founded
1995|1995: JavaScript and Java are released
1996|1996: Hotmail launches web-based email
1997|1997: Wi-Fi standard is introduced
1998|1998: Google is founded
1999|1999: Blogging platforms gain popularity
2000|2000: Dot-com bubble peaks
2001|2001: Wikipedia is launched
2002|2002: Friendster popularizes social networking
2003|2003: GitHub era begins with early DVCS ideas
2004|2004: Facebook is founded
2005|2005: YouTube is launched
2006|2006: Twitter is created
2007|2007: iPhone changes mobile computing
2008|2008: Google Chrome is released
2009|2009: Bitcoin is introduced
2010|2010: Instagram launches
2011|2011: Siri popularizes voice assistants
2012|2012: Raspberry Pi makes computing accessible
2013|2013: Docker is released
2014|2014: Kubernetes is announced
2015|2015: TensorFlow is open-sourced
2016|2016: AlphaGo defeats a world champion
2017|2017: AI and cloud-native adoption accelerates
2018|2018: GDPR reshapes data privacy
2019|2019: 5G networks begin deployment
2020|2020: Remote work reshapes software development
2021|2021: NFTs and Web3 gain mainstream attention
2022|2022: Generative AI enters public awareness
2023|2023: Large language models go mainstream
2024|2024: AI copilots become standard developer tools
2025|2025: AI-assisted software development matures
2026|2026: The future is still being committed
"

  echo "$HISTORY" | while IFS="|" read -r YEAR MESSAGE; do
    echo "$MESSAGE" >> timeline.txt
    git add timeline.txt

    GIT_AUTHOR_DATE="${YEAR}-01-01T12:00:00" \
    GIT_COMMITTER_DATE="${YEAR}-01-01T12:00:00" \
    git commit -m "$MESSAGE"
  done

  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/${REPO}.git"
  git branch -M main
  git push -u origin main -f

  cd ..
  rm -rf "$DIR"

  echo
  echo "📖 Timeline created! Check your commits:"
  echo "https://github.com/${USERNAME}"
} && _

unset -f _
